<?php
namespace frontend\models;

use yii\base\Model;
use common\models\UserModel;
use Yii;
/**
 * Signup form
 */
class SignupForm extends Model
{
    public $username;
    public $email;
    public $password;
    public $rePassword;
    public $verifyCode;


    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            ['username', 'trim'],
            ['username', 'required'],
//            ['username', 'unique', 'targetClass' => '\common\models\User', 'message' => 'This username has already been taken.'],
            ['username', 'unique', 'targetClass' => '\common\models\UserModel', 'message' => 'This username has already been taken.'],
            ['username', 'string', 'min' => 2, 'max' => 255],
           //用户名正则匹配
            ['username', 'match','pattern'=>'/^[(\x{4E00}-\x{9FA5})a-zA-Z]+[(\x{4E00}-\x{9FA5})a-zA-Z_\d]*$/u','message'=>'用户名由字母，汉字，数字，下划线组成，且不能以数字和下划线开头。'],

            ['email', 'trim'],
            ['email', 'required'],
            ['email', 'email'],
            ['email', 'string', 'max' => 255],
//            ['email', 'unique', 'targetClass' => '\common\models\User', 'message' => 'This email address has already been taken.'],
            ['email', 'unique', 'targetClass' => '\common\models\UserModel', 'message' => 'This email address has already been taken.'],

           // ['password', 'required'],
           //['password', 'string', 'min' => 6],
            [['password','rePassword'], 'required'],
            [['password','rePassword'], 'string','min' => 6],
            // 密码和重复密码比较
            ['rePassword', 'compare', 'compareAttribute' => 'password','message'=>'两次输入的密码不一致！'],

            //验证码
            ['verifyCode', 'captcha'],
        ];
    }


    public function attributeLabels()
    {
        return [
            'Please fill out the following fields to login:' =>Yii::t('common', 'Please fill out the following fields to login:'),
            'username' => Yii::t('common', 'Username'),
            'password' => Yii::t('common', 'Password'),
            'rememberMe' => Yii::t('common', 'RememberMe'),
            'rePassword'=> Yii::t('common','rePassword'),
            'verifyCode' => Yii::t('common','verifyCode'),
        ];
        return parent::attributeLabels(); // TODO: Change the autogenerated stub
    }

    /**
     * Signs user up.
     *
     * @return User|null the saved model or null if saving fails
     */
    public function signup()
    {
        if (!$this->validate()) {
            return null;
        }
        
        $user = new UserModel();
        $user->username = $this->username;
        $user->email = $this->email;
        $user->setPassword($this->password);
        $user->generateAuthKey();
        
        return $user->save() ? $user : null;
    }
}
